### ISSUE TITLE
which way to go?

### ISSUE THREAD

**Issue by kegl** [paris-saclay-cds/ramp-workflow#200]
The questions I'm asking myself after the discussion https://github.com/paris-saclay-cds/ramp-workflow/pull/195.

Why do we want to use RAMP? What's the added value wrt what's already in sklearn? I'm really curious of everyone's answer cause which way we go may depend on it.

Our (real-life data science) main use case is to **run non-standard workflows and experiments**, while keeping two things:

1. Separation of the experimental setup (data, metrics, workflow) and the actual work of optimizing the solutions. This is a management issue which we assist by a tool. In my practice it's rare that we use simple classification or regression pipelines; there is _always_ something non-standard when you work on real data science problems (it was already the case in my CDS experience, and it's the same now). This is of course very different from the teaching use case where first need to teach the basics (although elite students in the acrobot hackathon were thanking us for not proposing yet another boring kaggle challenge where all they had to do is to hyperopt xgboost).

2. A standard way to format the experiment: cv folds, double cross validation, the file structure of the starting kit, and the file formats (e.g. of the score tables). This is also really helpful for management: things look the same from one project to another, we can get used to it. Again, this does not seem that important for teaching since students will only use the tool once or twice.

Now, I can see the two use cases (teaching and real-world data science) diverging, and it's possible that a certain point we'll need to fork. I don't think we're there yet, and I'm very much for making the effort to keep the project together.

Another possible answer is the **data challenge feature and ramp-board**. If that's the case, we may think about a redesign where the only feature we keep is file submission, a script that reads those files and outputs scores. The current RAMP is a lower level instantiation of that, it manages cross validation and various "built-in" mechanisms for scoring (like cv bagging) that are specific to the current RAMP train-test script. If you, for example, want to use `sklearn.model_selection.cross_validate` to handle all this, we may want to have a higher level abstraction in ramp-workflow which only assumes the submission files, a custom script to run experiments, and a score outputted for each submission in a standard format. We also have another use case for going this direction: running RL (AI Gym) simulators to "score" a submission file containing an RL agent. This would require more thinking and work, and I think we are not yet able to make informed design decisions. What you guys (those who use RAMP for teaching) could do is to develop a pipeline-based script for teaching, following the current file structure and output formats as much as possible (but not more :) ), while we're developing the RL experimental protocol, doing the same thing. Then we see if there is anything common in these, and what the common abstracts concepts are.

**Comment by lucyleeow** [comment]
Hi @kegl, thanks for your patience.

I wasn't aware that you were still so actively using RAMP. I understand your desire to keep all the features in that case.

With regards to the workflow I suggest that we add a sklearn pipeline workflow that just takes in a sklearn pipeline in one script. This will be used for teaching and satisfies our desire to make things easier for the students. I propose to then convert the teaching example RAMP starting kits (titanic, boston housing, air passengers) to use the sklearn workflow since these are just used for basic teaching.

With regards to using `sklearn.model_selection.cross_validate` - we can just think about this for now. Yes, as you say, teaching and RL requirements may diverge - in teaching we want easily maintainable code with just the basic functionalities - but this can be continuing discussion.

Thoughts? cc @agramfort @maikia @glemaitre

**Comment by kegl** [comment]
Sounds perfect, thanks @lucyleeow.

**Comment by agramfort** [comment]
+1 for me too

>
